# Generated by Django 5.2.6 on 2025-10-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpUsuario',
            fields=[
                ('usuario_id', models.BigAutoField(db_column='USUARIO_ID', primary_key=True, serialize=False)),
                ('rut', models.CharField(db_column='RUT', max_length=12, unique=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=120)),
                ('email', models.EmailField(db_column='EMAIL', max_length=120, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20, null=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'ADMIN'), ('CORREDOR', 'CORREDOR')], db_column='ROL', max_length=20)),
                ('password', models.CharField(db_column='PASS', max_length=30)),
                ('is_active', models.CharField(db_column='IS_ACTIVE', default='Y', max_length=1)),
            ],
            options={
                'db_table': 'SP_USUARIO',
                'managed': False,
            },
        ),
    ]
