# Generated by Django 5.1.3 on 2025-11-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=120)),
                ('ubicacion', models.CharField(db_column='UBICACION', max_length=200)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('activo', models.CharField(choices=[('published', 'Publicado'), ('draft', 'Borrador')], default='published', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PROPIEDAD',
            },
        ),
    ]
