# Generated by Django 5.0.6 on 2025-11-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='activo',
            field=models.CharField(choices=[('published', 'Publicado')], default='published', max_length=10),
        ),
    ]
