# Generated by Django 5.0.6 on 2025-11-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_propiedad_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpPropiedad',
            fields=[
                ('propiedad_id', models.AutoField(db_column='PROPIEDAD_ID', primary_key=True, serialize=False)),
                ('rol_sii', models.CharField(db_column='ROL_SII', max_length=20)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=200)),
                ('comuna', models.CharField(db_column='COMUNA', max_length=80)),
                ('region', models.CharField(db_column='REGION', max_length=80)),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('DEPTO', 'Departamento'), ('SITIO', 'Sitio')], db_column='TIPO', max_length=20)),
                ('sup_construida_m2', models.DecimalField(blank=True, db_column='SUP_CONSTRUIDA_M2', decimal_places=2, max_digits=10, null=True)),
                ('sup_terreno_m2', models.DecimalField(blank=True, db_column='SUP_TERRENO_M2', decimal_places=2, max_digits=10, null=True)),
                ('dormitorios', models.IntegerField(blank=True, db_column='DORMITORIOS', null=True)),
                ('banos', models.IntegerField(blank=True, db_column='BANOS', null=True)),
                ('estacionamientos', models.IntegerField(blank=True, db_column='ESTACIONAMIENTOS', null=True)),
                ('estado', models.CharField(blank=True, choices=[('DISPONIBLE', 'Disponible'), ('VENDIDA', 'Vendida'), ('ARRENDADA', 'Arrendada')], db_column='ESTADO', default='DISPONIBLE', max_length=20, null=True)),
                ('precio_ref_clp', models.DecimalField(blank=True, db_column='PRECIO_REF_CLP', decimal_places=2, max_digits=14, null=True)),
                ('imagen', models.ImageField(blank=True, db_column='IMAGEN', null=True, upload_to='propiedades/')),
            ],
            options={
                'db_table': 'SP_PROPIEDAD',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
    ]
